language: node_js
node_js:
- node
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: pbX6ztVLAMYDm/1GfBP2HwaK8MyLhyn6gOAObaUEIz/5QYWmuNmG/gRfKrc547I0jKmHaRpkptGgFTxEJsrY3tXPq2p8ng83DrwP+Ljwxhw/skhHqim8xWTyeMMBQBs/Lpsig2gzEIzbQoLsVomWMaA1HjU0thGtm+9RW+61MKl+ClL3QFxLSLuk8meRPaHhaLl2i2J92I4G6eEcXeapRZT4btIg1gpqM01Zmj3IDbNbi1LYJBcZhUsqaoh9X5n2gxg/zkMLjTJsHxZEOh3QwBHSIgsp0shK3pyOvCktBEQifF09uMWR82Ngx+L21FTtna2JWKqgUrq+WUKDw3oj45asBW3auxrmMNYfVK4EEoqStJYVvcAg2srM8pOsQT8oIq84V3RFD61nP97sq8BtZ3Oj5iSVhOgNCjOk/1hS/KXSRZ2Qj1W8pi3EJGvfI0WVmZu/gJNCAA1K69SYuUL0ZrZHuxlCoknFDJr4b/nQ8zRedU4Mgtnu7t/R7wKFTWiAHtzdp8L2ytZWsdCfkHUlqa1q3IOowFOdXg25H54Jt3VJv214VqMCF61mAu03I5AbIcfbThCaF6z/lbFDdTBZGR5g0MeIDN4s0HdMaG+u192SkIvmInGwNrTIwhadfBMxII7LdrWTpueaEhXJIgzWGG9cY+1YAc70k3zrWS26un0=
  app: salad-bowl-web-app
  on:
    repo: VatsalRustagi/SaladBowl
    branch: master
